version: 2
jobs:
  build:
    docker:
      - image: docker

    steps:
      - checkout
      - run:
          name: Install tools
          command: apk add -U gpgme unzip      
      - run:
          name: Download and install
          command: |
            wget https://s3.dualstack.${REGION}.amazonaws.com/aws-xray-assets.${REGION}/xray-daemon/aws-xray-daemon-linux-2.x.zip
            wget https://s3.dualstack.${REGION}.amazonaws.com/aws-xray-assets.${REGION}/xray-daemon/aws-xray.gpg   
            ls -lh         
            gpg --import aws-xray.gpg        
            gpg --verify aws-xray-daemon-linux-2.0.0.zip.sig aws-xray-daemon-linux-2.0.0.zip                  
            unzip aws-xray-daemon-linux-2.x.zip      
      - run: 
          name: Build
          command: |            
            docker build -t   miki79/xray-daemon:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push miki79/xray-daemon:$TAG
            